# -*- coding: utf-8 -*-
"""SENTIMENKOMEN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ChMOJMKCJgIyfAO0hbzUMo1tR_7lzOQg
"""

import io
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from google.colab import files

# 1. UPLOAD DATASET
print("=== LANGKAH 1: SILAKAN UPLOAD FILE DATASET ANDA ===")
uploaded = files.upload()

# Mengambil nama file yang di-upload
file_name = list(uploaded.keys())[0]
print(f"\nBerhasil mengupload file: {file_name}\n")

# Membaca dataset ke dalam Pandas DataFrame
df = pd.read_csv(io.BytesIO(uploaded[file_name]))

print("--- Preview 5 Data Teratas ---")
print(df.head())
print("-" * 50)

# 2. PREPROCESSING & SPLITTING DATA
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import confusion_matrix, classification_report

# Mengingat kolom di dataset Anda adalah 'Instagram Comment Text' dan 'Sentiment'
X = df['Instagram Comment Text'].astype(str)
y = df['Sentiment']

# Membagi data menjadi 80% Training dan 20% Testing
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

# 3. VEKTORISASI TEKS & TRAINING MODEL
# Mengubah teks menjadi angka menggunakan TF-IDF

# Agar AI membaca kombinasi 1 kata & 2 kata sekaligus (misal: "nggak tertarik")
# Ditambahkan lowercase=True agar semua huruf otomatis dikecilkan
vectorizer = TfidfVectorizer(max_features=3000, lowercase=True, ngram_range=(1, 2))
X_train_vec = vectorizer.fit_transform(X_train)
X_test_vec = vectorizer.transform(X_test)

model = MultinomialNB()
model.fit(X_train_vec, y_train)

y_pred = model.predict(X_test_vec)

# Menggunakan algoritma Naive Bayes
model = MultinomialNB()
model.fit(X_train_vec, y_train)

# Memprediksi data test
y_pred = model.predict(X_test_vec)

# 4. MEMBUAT & MENAMPILKAN CONFUSION MATRIX
labels = sorted(list(y.unique()))

# Menghitung Confusion Matrix
cm = confusion_matrix(y_test, y_pred, labels=labels)

print("\n=== LANGKAH 2: HASIL EVALUASI MODEL ===")
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

# Visualisasi Confusion Matrix dengan Seaborn Heatmap
plt.figure(figsize=(6, 5))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=labels, yticklabels=labels)

plt.title('Confusion Matrix - Sentimen Cyberbullying', fontsize=14, pad=15)
plt.ylabel('Aktual (Kenyataan)', fontsize=12)
plt.xlabel('Prediksi Model', fontsize=12)
plt.tight_layout()
plt.show()

# 5. DEMO
print("\n" + "="*50)
print("=== LANGKAH 3: DEMO INTERAKTIF ===")
print("Silakan masukkan komentar baru untuk diuji oleh model!")
print("="*50)

while True:
    input_user = input("\nMasukkan komentar Instagram (atau ketik 'keluar' untuk berhenti): ")
    if input_user.lower() == 'keluar':
        print("Demo selesai. Terima kasih!")
        break

    # Prediksi teks baru
    input_vec = vectorizer.transform([input_user])
    prediksi = model.predict(input_vec)[0]
    probabilitas = model.predict_proba(input_vec)[0]
    max_prob = max(probabilitas) * 100

    print(f"-> Hasil Prediksi Sentimen: **{prediksi.upper()}** (Keyakinan: {max_prob:.2f}%)")